name: Test Python Package

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        # Set the python version to use in testing:
        python-version: "3.10.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.6.1
        poetry install --with dev

    - name: Run tests
      run: |
        poetry run pytest
